spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.application.name=api_cursos
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.hibernate.ddl-auto=update

security.token.secret=${SECURITY_TOKEN_SECRET}

token.sonar=${TOKEN_SONAR}

management.endpoints.access.default=none
management.endpoints.web.exposure.include=*
management.endpoint.health.access=unrestricted
management.endpoint.health.show-details=always
management.endpoint.metrics.access=unrestricted
management.endpoint.prometheus.access=unrestricted

