name: Api de Cursos Application

on: 
    push: 
        branches: [main]

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup Java
              uses: actions/setup-java@v3
              with:
                    distribution: temurin
                    java-version: 17
            - name: Build project
              env: 
                   SECURITY_TOKEN_SECRET: ${{secrets.SECURITY_TOKEN_SECRET}}
                   TOKEN_SONAR: ${{secrets.TOKEN_SONAR}}
              run: mvn clean install -e
            - name: Login docker
              run: printf '%s' "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            - name: Build docker image
              run: docker build -t ruanlgomes/api-cursos:latest -t ruanlgomes/api-cursos:${{ github.sha }} .
            - name: Publish docker image
              run: |
                   docker push ruanlgomes/api-cursos:latest
                   docker push ruanlgomes/api-cursos:${{ github.sha }}
    deploy:
        needs: build
        runs-on: self-hosted
        steps: 
            - name: Pull image docker hub
              run: docker pull ruanlgomes/api-cursos:latest
            - name: Remove old container and run new container
              run: |
                   docker stop api-cursos || true
                   docker rm -f api-cursos || true
                   docker run -d --name api-cursos -p 8080:8080 -e DATABASE_URL=${{secrets.DATABASE_URL}} -e DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}} -e DATABASE_PASSWORD='${{secrets.DATABASE_PASSWORD}}' ruanlgomes/api-cursos